from ErzaScarlet import (DEV_USERS, VILLIANS, DEMONS, CROOKS, ASSASSINS, telethn)

IMMUNE_USERS = VILLIANS + ASSASSINS + DEMONS + CROOKS + DEV_USERS

IMMUNE_USERS = list(VILLIANS) + list(ASSASSINS) + list(DEMONS) + list(
    CROOKS) + list(DEV_USERS)
